spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wu_project
    username: root
    password:

  mail:
    host: pop.gmail.com
    port: 465
    username: wuxingshi05@gmail.com
    password: wuxingshi666666
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/*.xml


